apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: argo
spec:
  parentRefs:
    - name: envoy-external
      namespace: kube-system
  hostnames: ["argo.k8s.krapulax.dev"]
  rules:
    - backendRefs:
        - name: argocd-server
          port: 80
