apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-krapulax-dev-production
spec:
  secretName: k8s-krapulax-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: k8s.krapulax.dev
  dnsNames:
    - k8s.krapulax.dev
    - '*.k8s.krapulax.dev'
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZXZBTnEyNVJjM05CaHd4
        Z3ppOVhlV2czL2RFMUJXSHVpVnVtend5VEF3CjBwS29SaElRZ211bExjOGZocDcr
        UmcvSFBUM20vWTRtRjluaVQ3eG1ha1UKLS0tIHVZdjI4Syt4b0hZbEFRWnpLc1FO
        RXdGZ0J1aXhYcUZVM1lodUVrTnl4aWMKMzVhKS0gxVSWWyMZhMYQ/ROUDBFeaItU
        IAKTJuJylTdbghQnTIQwkEpYrP+SHVFr9+N8g/TZj+fzafMCr2z1gQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:38mkoljeM/lduMyZ8cwP3SK++LXITvjvp2sjhxCbSva/mIUR3qs+i/f2eoIwUGKEWbwZZ00xNp+VmtsNI7wOK1PzWnRp93wCMbjqakslsZWvxkbjwsqYjNBb7KlGBX+DSi8RDs4K/aOHE48PJKWjgLyXX+GP8Xfj1PIkbE0Zvr0=,iv:wsQIKWaWQkla8wPWf2FhpYsdQCMgQ3VywJBf8rul6Fk=,tag:/BghE2JODOvCQpgZslncPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
