apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-krapulax-dev-production
spec:
  secretName: k8s-krapulax-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: k8s.krapulax.dev
  dnsNames:
    - k8s.krapulax.dev
    - '*.k8s.krapulax.dev'
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXUDJYUFJEYmd0QVFXMTFY
        VUd5OVFkdjFzUTBlSFVQbGxqc2h4bGRZM1RrCmhZMVFGOWlYV0p0eUxXRmIwWGw2
        OGhLcnpucTFaS2pOYW1MYnBRaU1KSGcKLS0tIGh5U2F4SXhQRmtDVkJZcm1pWWg3
        LzMxcC9YZFJwN3ZoUHRCb3huZVZ0N0UKkFMwm8s/0nT8oWAJCZ3jlM9tJOB08xzq
        o9+w0EZ6qaoe1Olt/1NybNQ9aEBsdaCbLWGPVm6cJGehmpchhM2J/A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:pR+h9oAkcTM41sLnw6lYVe5R7TqyHpyJhwh8lmOnXbd00dOiey2Mb8Ev0UD8zHCIf8OjHKlGML/w74PHYuqL0M3xA2H16G2PxRDscHUjlbUyLmkE7UAgK9AICFQctDyyO/lWYhfbtSxEY2p/rcAyp74o/s3Bh4HIq2LIsRM8aPs=,iv:lPvF6rcOyDQ4Qv8SJbFy1uKjyZ11BYUq9r38PGiDJFc=,tag:7aTw/80AGPcuYXXge91BdA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
