apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-krapulax-dev-production
spec:
  secretName: k8s-krapulax-dev-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: k8s.krapulax.dev
  dnsNames:
    - k8s.krapulax.dev
    - '*.k8s.krapulax.dev'
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrek9DbE55L2h5cWIycUM1
        QXd4c3M4bGR1c0FibGFDWlBzdmFRUXpEdlIwCkxYR3lqSU55MTJ2Y1JQbVQ1d2JP
        T0lQY2JoMkVwT2VmbmkvanpFNlFNOFUKLS0tIGFmY2VUWU82NEFZZFcweHh1bmFB
        dDdqYlNoT1FrZFpxenl6cmtMOXlJRWsKNyKZINg8waS8/+mGjiJtCXwHUJvcGyOV
        9+fGczKINHPbUB7w5b4fNmoOcRwxNypvTao+C+QsZKATWuoyZNHtEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:35Z"
  mac: ENC[AES256_GCM,data:+glNh7bBPeXYNEMLZdNLJ7Gpe6hsCEOztlJOTB8s3UUlSIj5Xob/tTDc32OzUu3AtCpsCEnYr2ieuqjYq2G5OnbyXHb8nvW6TeM0CXBBfemdOysZD0D/HxDBGIuB/A7NzYWG5nc6wITDyXrocUHz+hCCiPOxP6sYZZoG2PpUhi0=,iv:tDN7ZTm2Nh4Du+J7mrwXcdo/vBm3uGgZQ3JK8OEcXq4=,tag:DFZt7JxmDOZcAaF5nf3VRQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
