apiVersion: v1
kind: Secret
metadata:
  name: github
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: ENC[AES256_GCM,data:wDUB,iv:vnQDDwLKDAmQTjXCmzfTOzskZ9lnAqK8wvctJXgC6gU=,tag:rqwoWEC4rlirLYUZYyNVgw==,type:str]
  url: ENC[AES256_GCM,data:rVDH+PZTjFonpxzV4upyZn/cnhMesC0=,iv:GI1guA/F280Wjx0SFrzgOxqxZuFvW1uieXXM9aytJuo=,tag:XsjIKUWcu1cyO2KmN0ggTg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WkxYVjBOTzRHeXBLbXhI
        ZWZDSjdWWU4yUWtDbVQ2SFhGbkdEdHkrd3lRCmRDSWZDU09scVlkM2Y2UkwxZ2c5
        L2RvNlRLQXhnc1FONzIrTXkwN0xNNFEKLS0tIGMrVzJrMG1DSUNZYVdUZ1dzZ1Vq
        UjVXejg3eWlqSDRJRzNSUVhkQmpaNG8KE2lxXDwp+9WvutaGeRgaVLCm9qOcWE/+
        g80Ja0CJNVHZtUW8CxQtLvztZf5TRYrzvzGL6YX3QMuD330kBWXt5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:jmcBaDoBp+a90A5rY8y5peQDAHZIc1xm0GM3G1Uep+bsJfTVZPQdp1RvTB7KwIfJehN2mw4lTRwo0TKtZsDWCslByEI7MJrkg/Vs71WTEPyKmDNRzScDyQa4TgfaRYSupEsROv41P6PAXMRweWHWY4zCuY3Ztsldt2WJtWxo6wQ=,iv:whsZSzZPNEM/zWzQE4iCqA1nADyhoDKUeuUftHmlbW8=,tag:wyXPTo4wAeYOqsPJgoVKJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
