apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:h3loTJz4sJPoB3JV6QriJMSlHHs6EQ65BuDESRAhIRIPa1mjq+pmWQ==,iv:Vzz5IkAs9iTSh1jhziJ0+qXdbga7AbkV3KvTIGEc2BE=,tag:xF3frBT1N8ZN+WRu8EEuKQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArRERBU3hDekY1aTFGZ1pw
        aG5iQ2NHSHZ5Z1FLSVU1VEdTK0xVUm5jblVjCng2b09scDhBdHdvZUFlSm9Bb2c4
        NHNIdVFncEFXUjhFdVJrY3k0bXc5bmcKLS0tIDVlb25zMzJXeWhuRng0ZU5aZDlW
        MXRMdVA5dTJxYVhlSllYaVVjVWNDelUK6zx/w61BZQ+jhjOpQxyLMybo+jS7td7N
        HDjMO33T7x3OkWogIXlN5ciNsIMklq2fkVsy/Vbd3PHeJDH2nHRqeA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:DSpXmbrsZyz+5vrUN4nzCixMMsrFqmKj7lktpC3URKkQkuOOqoJhxDqERBh7Mr8rj40bavtpitMH+3mt3LwBJ2BRFKSLUQzuTfIOqY1rTn4o0ejhG2JOfdsXF6tPFG+DoF66CwTpO95Bix0UwmZZK6JkqGgOxhaPE7v1EfzXDU0=,iv:rxz7MyUwgoVYz7RNObJ3byItRGptBV7d64K4NsKvuJk=,tag:E59TZN7JYYNtJdv6Cw1Rmg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
