apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:PYwb5UQJIHNgBrBZ5MPt13R2EqlP3kMKl24yfh/iTmSVlFbdwNUG5g==,iv:5xhdVUWyT4hfgbYwZYWt4/SrNGsrgwIWA0IvDRB5Q/8=,tag:4wbubIQcsDDYqB5vs4DoCQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYTGM2QTYrSUhhWmhlUks4
        cEFjbHpkTjFWMWxDR2RKWG93UXdSdUJReUhNCjRnY2pYeHVSUWlwNWh3ejk3REJV
        VWFmYlp2Tk50dnhmVmxUMkJ1NEtCUXMKLS0tIDhSbDQ0cTh0eHlCOWNzYll5dHgw
        QWwxc2xaNyttMUFMTzNCKy8wcnhGdWMKXPF0vSTeiiSwjvhhgUYGh7irCEsLgc1+
        bMYuj2wtzGeafgmrvPaNQshwGahx/4vwOyeHdYAQIJEril4yzuYt2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:d25+R7ohffW04nTNNmYMGBD2YF7CwfOu0PjdnZwkINEsUZad9e1WIcluZJ6MyRJhu5oShUBrPjoiIeJ4Ko2eC/GcJP/g34fovbGasGNd80awJJpQG+kLNmSvKTNv6J1sKKTGamLBEpNGhOi8GcLoUnLswcMrJ0rBsG0Mju+fAOU=,iv:ou4nmaNFmdvGFrW1dWwSBNZHx0bTavT8uudFf61VtYU=,tag:BrptoLhmXNT1AceN4phwfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
