apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:fbky+OyjYWuH+vRUCRcL28D4SVZfzIVS4ZOwEyuVK9SvsSW0sIfAxA==,iv:TYRwi1x6toXP/wd0jI8jCKY6ZvDyqm7h0jGcuGBKBmI=,tag:9RKnpb4i31vbSpTTfowgjQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVy9MeFBSWXFwY1V4ZFBW
        M1FXbE42WHZWOUhaTEd5NDlWOC9laml0WkR3ClFBcnJITXE3c3J2WGdVb1AzREJx
        cWUwTkJwcTJDQllPZkRKWEM4SDdFSmsKLS0tIElTVFQ3NmFGNWxVdmlTOGFoTUlh
        a0J5Q0JTbVFTNWEwNHlLRFlRR29EeDAKYVdSNDM9HlxZoHGzsnoVWrYB1smesvJ/
        rA7dYPVBIjG/5yZJCGQarUWxaw5O6rydmHBo+7YlTJsmrh0lG9n5iA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:35Z"
  mac: ENC[AES256_GCM,data:cm/SogAPpSrt98YGEL0rDsdiKOeMhTf+alN5xoREHRfGg+HdQYWLBoqXt7vD79tFyHhTzqiGQesEz1HRKEPlnGoukC4kZuzgU1lo080Ye2UGy30i651hI+ZohHzhdfZ742MlUCW+EmEbCt8tpWAYG63zOu+Yuxz9I0aPJ0ZkYqg=,iv:fdVu39oz80SwO9WdPStrBb9aL1tiCaY5Iu7hpTDv0uY=,tag:vC/GS2Sm72A502C5/k7dEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
