apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:2Bc8ZMJt0jh4e6moUP6Bi/7aNOQqC+nt6PRb+6aeRN5kEsEYgQrzHA==,iv:XR/ZMMn5LTfDpOXdTDlyBxLEfI68TsBRSGbFxG9vu8k=,tag:brUwhX255cjZvcIijeqSLQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1aWtNNFJ1N0RzdW5zZnBh
        enZadVVNRzNpZXVac3FhYnZNN1gzQW1nSFNrCjl6OHVNMG1Tcm9MeUF3VVJ6Vk4x
        MElMME5VWlhEWGxpT01YeVY1RGVOV0kKLS0tIFNjOS9PZGtDZVJEb1RRVWZYNUJV
        T21ZbWEwTHVTNk15NVR2WDlJTytkZ0kKAINmC/U4XKeq/cH5UFk8NKPDShgrDUCp
        38uR/V29L4oys5Yy1Wwjh1K7yOUfxzvz3K3tgJjMRLVlYm2Nz3ShQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:03:55Z"
  mac: ENC[AES256_GCM,data:Bk3TiJ/MbWacxgc3pl89DrJQaWmca9w0yhSTpIsWRjTQDromYPwjMzZK9R9LhypksJ3Kr5hM0QujlhLOCq3m8hG0p21vOL7Uqa6Hy0s2ey4aEjv0duB7nXkmVTTDbq3w2nZoAYRBgoFeOkeSBblfKbLI1koqA8xsbuL5E5FeFeM=,iv:GneCtPMATlAOEDL4bbeVf7skAWd1WFgjsT21e1VEKA8=,tag:6dcZwyf5bQct6bH21izF/g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
