fullnameOverride: argocd
configs:
  secret:
    argocdServerAdminPassword: $2a$10$mQ3DfkrMp0OsbPIq8QJ92.7Gm6vYSkfU9v6zT3zhafLhVZG/JLB2i%
    argocdServerAdminPasswordMtime: 2026-01-04T15:03:55
    githubSecret: aaebd543422ed4c2f5c8e89ad47fee36
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWTdRby9Xdm53Qlpzcy9Z
        eEtPc2F4RmE1U0lrMVNva25wQmFuOWJNcFNnCmcyQUVMbHAxSUV2K3Z1ZGtOWitX
        WGJSTld5eXFEOEJ5WmdsVUJxNmtmeWsKLS0tIHg1QStBKzQ0SHIyY0VuOW9DRkRy
        ZWNuWDE3WkZkbUpaRXQ0SFdVVy9HS1kKeqiud+9ui7goIsCMZTRg5r4DQTlJaXmh
        yV6KiFABAWEnfVzZaozR3P2cSdlCnljv53Uq1txfXObkjlSi1ZyXGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:03:55Z"
  mac: ENC[AES256_GCM,data:OSp/fgpeAiUHpdegpzVlVw3RTcCjNaAbZFC4CMZlM1MCwnelBTjcdKSIYnSa7nqeD6ZydPX2l8DJQqcPSwHMPjIpik6Z0ohGTpg63Zpcen/TaXSRq4zbKjDQFLtB6zlLZgIBWBe7ebH2Fe5Jv7LatIlE76xlzQc7ogBT1UWZ70w=,iv:MqQcwbzHvV0I70erKXgOmJhEHWBDeyJkJHJS/f0hv5Y=,tag:MpG8l7sSaf7HGs+ACCbB+A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
