apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:HHST7YFccmK4rnnqa4WQGu38FkE6bnrI+XMM05Ptkg2+Vpf56dV3Gn6jZ3XsfLG69jIyNf1LnTCjmD1RgdPFwqA769EBYNU8NSMR,iv:Zdo2rT6MLBHBUJvpgNFgc/c0MmBXueJcrdkr6xmhCso=,tag:oIiSOtmjA4Dg64Iqh/R6sA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaOWdxNEhxY3BZV0JtM29l
        Lzl5V1ZSOU9NOTVpc3hpcnJUZHdUbkFnMGlBCnFVNWQ0Z1A3SnVnWFBtTmFNbHUx
        d2RNc1F5bDlqUUFkVjAwcTU3MmJtMXcKLS0tIC9LVXJ5NlhwYjNBT1hXQThna3c0
        UlFLMDZtSFY3ZU8wb0g2TW5nNlBlbmcK/uPPXWN+PSDoP+nMmACcOqnQ/a6aBv/S
        bmTrobt6GMVQu8TBKCaMHTX38PeQl6YA8ovIjvpRZSa4SYMtiJxd3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:tORTeKBd3ZYE2I2Uj6K6qkEdbvkyR8SkAqvPugZ9kG5QSI4Mk9isWseyyn0d97Ygkc3G6JuLckq8exyeSt4IahhsHHth3SnfwQ9qfu539Ai5D/bo/utb9TruO+cEPcgkpfWNi04tqxFULOuNZP3Ho73VKa7inISXqCooaYxrpqs=,iv:a7Sg4lGFBhVdeYY/Y9q/TlCkV4KJbKnP0Yx8E4wcb8Q=,tag:Z0rCimutzYOY+INkcTYOlg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
