apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:H2fCpnLbSyWDPweqTrUrvj5MnsrKnPFjSitHaXEwpZ2r/lJtMY3Aoyc4PY/pTUjst42NGw5KyNfL6ewnoQ8QzLg0M0riaDyE15tr,iv:ThzX5iAS/ay11siM7aOSniG30Z4jJ/RIf9CYv5V7pME=,tag:9/Z7jX7ZY7KN3cMBHkPixA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaYUF5MjlZLzg2cFk5RzB5
        Ymd1RTVHVHBGc045TnRUVFRUR2RxeVVMaXdFCkFoaFpHdXFMWkZtUXlyVHovR1g0
        bGVDWCsyOG9MbmFmZEpOa3JiYzNXaVkKLS0tIEdrWEpHL0tFY2VLdi9zbDVSZXBH
        YUdSV2MrelRodlRLdlppdHBHK0s4SWcKceF/OFERBLPsuepca7AcrI1nQtI8G2mV
        /iT5/EoZoOEg33dt0R3xiSvSGBG1ISM5EGRTO977m/6HXEA0fg5eqg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:03:55Z"
  mac: ENC[AES256_GCM,data:cmKl83Wle5+W9ICwG4pOqk8nq0WP/q4l2zTYaauAEmr5zuBlbEdYRiryUCjDmm7s0biVBQc2g0gHq3xwBzHDUgdtqINk3wX9vJfeV8kPxn/yzf0VJBYO6wWV6dsyrdIWwxX3Sowmd1rQf15yetBLH5V3XGvhkfgRrcEHyNFya54=,iv:xnp1+WOhKBXIMkJ3IhT212Fd9+IhLogHklQAOdTbS2Y=,tag:fHUgAT2qq5VlWZd6rHqg8Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
