apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:XORV1tNImgdbyBVAs5uXOsltcPOXnRNcTWofgP4S6HuClXYhyrwul4RrUzf0L3P0XGhKM4L1CIPZijW6dZX5CRXwfqhMVIFk0jfP,iv:bofYf0CBACyc+hgSMCq9l8jDThyy3OuhTKP3+C6t/vY=,tag:40VbiRGt52K/BWHD607Yfw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cWNwWmlEUjBxK1pnclVM
        cEJzU21iRUFXVklXNE9Kb3VGckhSTHpMVWk0CnhMU2xyVHFPa3BxcmZGMnFRU3pI
        QmM2VjFUMFdNOEdMdStWQkFreVVGdXcKLS0tIEwwNmJuNVpBR21yNXJnQXpDdkkr
        OCtYeXpqNXpIKzhvMkh2WjhHbW5maUEK34xs0k8amv7VO+L+VbTzq6ycC5U4Qjcz
        8ivkYHp/aO+h1e8/62yX06nOL/ff8eitpRjx+m7hVkZvxWHAdOfR/w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:XpchtThwKWXpj24Z2bL45bxQqBYoOQW//2w35Q0kbVTpA1yTq+rGCtqijW55IxnDDogwnnY+dZIrWzayc6E3wytHhGuhgrDBcqoB14WmjTsgVCnaa1EHMeh0SL0BWofh9WcluZeim/oYysZukc0UL6sBb1zHzco86TcwBObAPWs=,iv:jQl56ltWEhYx57xp9xcWZ3yPiWxs7qCT2AEWjuYklhg=,tag:obszxNl55TdM4V/pwZPJ1A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
