apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:9VpSBVT7jONh+ZDYHepdmDrAjq7nfy336iVsux92YVO7c5TFPT3f5HBm8wTYOYVlYCEWNx6FJo5ikPRhYiZfYaO9gmpJrv+UqlEh,iv:uRBldZOBN/WQvfBJZ+wMdWCR2YCtyfSpMJ7QbWQCPdU=,tag:ZooQiI6BTOw3G0nkA6WkWg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVjg1YlQydENHWitNeWJH
        ZmcwSUpTNENzUkc1VnEzT1JvUVFLY1pCZldZCi9CbmlQdTJtSEJicVJmclF4NWlB
        TCtVWXU3RGp5TU55dFkrY0hFVWtuUXMKLS0tIFp2SjdXK0t3OS9scjVMdnB3OG5m
        Qi9raVNkc1lDcTFsQlYvTTNMRldvaUEKaCJj/ioBAjjTM8asFkLkSKkFsnkESq0r
        wRiKb6yK1ISwo+VplPVNjkeE94u5Iccz1R4ZavaAb6eyaTw/Sk5wAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:34Z"
  mac: ENC[AES256_GCM,data:Vpexl2oLj4c0pn7RTdF7zpysYazNKO6CF3cbWbq+uInAXgizvtRYDvn0kqNuwhJoqfTAyi0ohNIHPla79/aCHS/3bNNIG1yPEfopN3f8S5/wctq/ySUAYsUYfQdS6+qrYLc2FpAlwJoMsh37jV49JIXci3y6dxzmyrsYpCAbV9Y=,iv:DoVck7RmhktoDnu1ITop9hgag7GXjsMeipArMQEBn5s=,tag:Awg8+VeGEZLCNpGHp6jeqg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
