apiVersion: v1
kind: Secret
metadata:
  name: helm-secrets-private-keys
stringData:
  key.txt: ENC[AES256_GCM,data:pdVCprhYvIVhjTQkI5msFgcqr/WiKEcEM6lhakXcPBck/cjUySNutItYGnPO0X5/rq0eCqYbA5Pwe7kJmdkUDhFBBZbMQpxv1O3+,iv:EawStqZo76Y+7ZrFf3bbfLGAqDxvnVxLOW12cCsVjSA=,tag:j9DWqj1k3Va89hIuRTjGlw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YU51bEtaOW1YQjh3SEJO
        K1Q0dmVDUmhDUTg2Tjc1S3FZQjI4T2MvSTFzClhqVUp6SmczNHZtVjY5Mm0wVTBm
        TDBkVGZVVGhSSXl4TEZHcWRvais5TTAKLS0tIElTNU9XK1luS204NStLcmZHT3ha
        VWxFRmYxNTJLWVNaN3JLQXY3aElBcXcKHqcxHKNSsN9W3yYIhupTKkCgZ58pCaHj
        gfrGKGeT1IQj2hsGeSLL2I8q7x4wvaNLZsQtpoCgwfaAyqjUcCwtgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:X8MZjxY1yN6cAAGgnRuNWCoWB4148wmuBFBpp8YCyc4wgs1fR6gc94+eoQZuVXcAfS1xqYwuwHO+4HycgfOIg5uQv7PhOW+TA2IsqvJQeGfayHdUQLeZIuIT2OmtnRV4rshxtOqObXnp/hvarjqdjlOz9LG11TQWjS85iydby/4=,iv:C53INmcpWl283G1KujaNv+zuhJYpwzO/+I0XzaxxzSo=,tag:g1pljBfaxuVmdOlvjSISbA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
