apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:6EPAY8Rp9BQr0sAZoiaYEnl1DWt/8vgJYvFe/7zXfgVLp4ZLc45EXdpeI3Nl0MWoj1VAU6eGPeD5plhimLOrYOH6bDkWRRfvmTYT53f5PNxIuGSvG9zFQnzseyBEm5V25rO5Iwu87+SJv7NuBq7x2dBl7OmuUVuMvO5go2H8bjhKDZ8BXzBFJqZACrwbb9PWZQeKPyITx5qT3RGIQsAT5Y/nYAaRV4nd6ZgIWqVFJ5Gwb2a0Zvc64aBPWi8vDQYORNY4H3MxKg83f92zlkEOb2MZeRfkfz7vqizqjyb57Nkf2Jr/fiTu2rHHC7HbJ1S+zMpymHKk0GuLOgT1URuCDGa2jJ9Y1rk=,iv:8uQ1L3P3dyvibq3errkPYs8tgvAnJKVXijOpD271Rx8=,tag:zznqAjMRxm7OjAVy3OxrbA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblQxV25FYlBCT1VYTzJT
        MGRWYVFlY3NMQmlnTjZQWTRWNzdlMkFpUGhVClE5Ynd0TlgvemJGQWR2L2JXZTJr
        QncwZE5HVnFVbXNsOVhKZHFFUWQwWWcKLS0tIHUwUW4zT1YzL2lwbTFyandxa2Vv
        RjlRa2RZZVdLSDlnSDZHS3J4b2dTZ00K0FQxCAjWyno7o2WS6bWQWBx62UuPYw+z
        6s3Ie853dQDM/K5SQSxOCXM3T56xrI/kRSqYvZxtetfa/3PCFU3lKw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:Mycq4urmWYJA0tjKM4VkNHR5YGQ1jvQmglQhk7eVQ3v3438Vc/jenUPfnUOl5FgjwYEDoQmpIUifPk6rpzY3R1r3/7hWpLFp9O1DEOCInSNy3m/TULWbn/wE+HIrO4JQuRnPT/O/4T2Xu7OxSHlYTNTX71/9tH/Isqd0pdXey/U=,iv:j9DjZM13XkOLBD3cD9FAF6ZGnmIV91sa9hXNKaRzzwc=,tag:i5yZpDeXevZy16ISIdGwbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
