apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:36ifREzXPLetKAEJySXq9NTGGvt//TqmEi0rjcQ9DIrpGXx+Hovqcbl8zoUf3qyfCDD3KA527KpHDEtwkwqG+ZbZhT6O5nUyct8z/hadLYPIPhQIR8EoxKgtWfcchD6MBa/2f4SnFoE0L0+FJZt0Y4ZUzYAhus5BPsz0YpCDo+ajNhWTUpVKQFQwMKnhtxX6IRWj01U5x2y9NEIyurOr6ELWlVn9TIv1pknEplOsgKyXsrFrQqE8Gszj9JViKgFK0n2gP89xET9ZAQDnLTRPCI4lApHnumE6c5ynAKfrQBoTHQ8sKez6Bw0pYJRK81OXECKtdcXUOLFV2Gr81uXkHIDKfaZUPRk=,iv:U8g5+rBZWaar+ymQaqHGLjhiSrR616htH4Zd/Ku70bs=,tag:IhzcuUeoXsIhSWltnX1kYg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSFBkbW8xd3FVRXdtK2hu
        ekEvN2ZsZGJnN0prNE53OGFwMjlWVUtnZlJFCllMQkFicHQ0c0pXY0l4ZWllRmJN
        REloanRCMGsrZzdod2FTdGVUYW5meGcKLS0tIEhNc0U0aUk1TGdIOWp1T21FTHN4
        NDFXWjdtRXpKYU4wS3V1SnRkb21ObjAK66ixsflQVQOvMSP06smOdFmlfzSoqoTf
        UfBjis0Vch9wrfltgX/OLzlbnq45gU6KYEOl9EaM3e+BL8ZdnxxvgQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:HHsL8P1aLeseFVeskYdUi6pM+adWmHGRFEgOmrzoyzMcT0xWfP53jsRWEnfIx0GDv0i/k7EtUINFO5kDfmKO+v8XI2XglovsiLQymvOSTKApFnwTYXYn4hRKKrvCkHnEt31X64KZ9GWmIyaq4RKvPIJUKUil8sl/98Bg/nUC71E=,iv:DQqacyH508mgghZsv7cICVrlfasLP65JP7j0J2pkvpc=,tag:b9CnmNeVehpyGRU3Yx4CCw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
