apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-tunnel-configmap
data:
  config.yaml: ENC[AES256_GCM,data:aVY0vwBu1QMrV8SfbYX9PRsnoGXX4hHBbDyL0hDtbUvKOXlrhFZWbf3VclpokeOFpuIiGcUd/tq5EN40SWZGyLTBxlGvo7FngOJueeh7um/cgcM2pY1+QuQa0Ggup6p9ZPg9ozRRaJclnWp77YP4H4oKqdb51Wh557zs2EmFTHGBjQ7tpVQmBUG1LFRnf3MOTPA2/nGaemk5m7MMAt+Oss66nvF4+uvcQdhCu8N7Y3mQX87ziHO1e59lrhikuF0SeGdJKKaC+MKsby9bBqH27AjXUm97DsXX32iFQ1qv1o043sfNduwhfzA/IyYexfeXoAxPaMcqVn6xV1HFT+PIEz1NZz8qWJo=,iv:QOi08vJz+1gyoj6RZ3fEKuvNM8/qsZRf1C3sxV6gGUQ=,tag:jwev46/vIVae5q+Hd8iEhg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqUVFIS1lZQVE4RDN4T08z
        RENqRjYzSkJNMUdNZ21LUlQ3UW93enVxc0NVClRnNm9kUG5mSHRwM0xITDZZeGZP
        NUpyNWZtZTA1R3RhVk85M0F4K0tmWVkKLS0tIDlnOFVZak9uUG5ESUNad0VMSjhO
        bXVkTmY2S0VNQ2dVV1hnWWd0eWN6RTgKpVXBmAjubr1Il1ev4xEyFk82+xRazfXr
        V6kRyEap8oxJ5k7tLBZbLMmeyz/a//4WjhTTpp31QB3KnzeR+sIevA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:t5e9mbRxNbTdXzq8NSiKKi1hClolalGnBFgtbD2Q3lUZrWLAdrKSy+86edWnBR2srVbf2YrbUyQ+67J3lSsRP67oaa6aMEj4n6vclWDYQjYcfURZfaw+2y/UT4cg79x8E7T24vXi3Sf0hRhAjZGtWwQ49RKV5wYNZaGkC7A7MVA=,iv:LzRkLxVWPMFckRYOCtzpUfeSF9dd3XQFDW9dL6QIIVk=,tag:fTeBkI/pkIlj7bhN9puekA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
