apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.k8s.krapulax.dev
      recordType: CNAME
      targets:
        - 096b810f-27c7-493b-9b9c-5e5e4749830a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlYW8vUnN2aWtpK201MXlY
        WHFmQ0QxdGtFZUwxRjM4aEM5bzVQTUdRY2pNCldtcTh5WlFkejkyQ3ZZSU5JL1pL
        RWhINEpwR0FwbWx3aGhyRkx1dVVXZDgKLS0tIFB5bS96ODV2b1hTRkVIQjVGS2FD
        TjYvL1AweklOZUN4eUZvNUVSNVNlTXMKgqx4w5ROmVIqUutbfPTl53gT99FOsXQT
        XuYO0Kb223bmBXe8HwH65fBUT3TMFL0TOOiPJhbHTjfMvSMWBmMH8A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:gvo32KWZRDxlUpT4tWOOx2+HFi7xs+xgwYF6YwEjd763zTCaWIs9EzzeecfDTexEmdr+4bIvD3fry6ZWNmMTf6VGBhymdWkc/TSEJsGkXMF4MRKio1cwSaI6LrVa/pxc8JH42X5h4qyHBB77PuxfwueR+L27XyZZvGzCqOzHMLw=,iv:6QO85ie9xb+z8N5vQF7Cc+BoOrZTWl7jJhKFev3KsvU=,tag:Wd7DzqEJB4cHMNRJtSHo6w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
