apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.k8s.krapulax.dev
      recordType: CNAME
      targets:
        - 096b810f-27c7-493b-9b9c-5e5e4749830a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2ZmRBMk1OWHVVeEJaVE1M
        TVhFVlJKa1dNbGJ1VTIzOGFUMkZKTDA4Qmk4Ck9QRVVNSTJGNUxFaElkdHFWZTBZ
        NkUzWVFOWURlYnRMTXF3ZkNyUENKS3MKLS0tIENrcHZRV2ZMcWNwMTFaVngyUEtG
        UTl5ajZkUjBhQWVNZFQrSzM1RUp6bGMKfVL3cNw81yhH1+Z9wotGYCoBIaB94EIr
        BCB/nUW0+efKbzcSF5yn5kAG6e3tivd8CzL3mhVB3oMQuDBtH6G7ng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:1RgR0X5m15GVpDoahiJ8uwuEYAoy2/5DT3ZhDLhwYvKsCo8wqsldQfaegGqENpmZoG9DP/WMpYQmXL4CY3HToXcrwsPlLh/E1nNfl2mqdqsC0zzrmrGSHSdp81SQwXH14u59fJ+gaXKSIrprPifOGMG0/terdq4zrBPCjawf3cw=,iv:hzndsJThukOFBQEDfr1OLAlxK+DPYxQsp/BcHXIS5Wk=,tag:7W8tQytes9K7Za7jqfjyZQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
