apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.k8s.krapulax.dev
      recordType: CNAME
      targets:
        - 096b810f-27c7-493b-9b9c-5e5e4749830a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIeVhYM3FHMFFKMlhnMS8v
        dHFQUldiVTk4eklYRmVzRnFNLytISWxrY1NzCklrOHVSQnExZ0JHbzkzL0Zvckgz
        bUpYQ2FaYitOdnp4SkpNWmtVZHNFV3MKLS0tIFF0c2YvVUtmTHZvclRIZmo2RkZD
        aTlZUGdqK0dSYy93bXpuVk1LT3hXM0EKwI2XeC67mdLZjASv41fZaCV2vFDRYIyk
        S8cH5GMwlgcqBWt7G1zIwFKe6FxMXBQ1FtvhuWLAXIiEiags1uP26g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:c716d7aMa2CaZ4ffIux3FAAWyj7sLDcCz6VoDjMZX1DRi9QHYWwAJeOMQPwpXVPnLnhk2qugAnD7EnIVT7dXGKi5KWJqCGa4SN6PfjVq14odQeol49OKngvLjdfsl7JJPbYeCI0IZsi3sJnNDVpRJIhVkPoFgtyUES/7ndRRK/Y=,iv:KwE1CTmf2Ww+xXVQhya2nVkoGMgE5zxg4Hcqfz7NHNM=,tag:hf3xUsh1IUudz3bVPwCDiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
