apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.k8s.krapulax.dev
      recordType: CNAME
      targets:
        - 096b810f-27c7-493b-9b9c-5e5e4749830a.cfargotunnel.com
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdWRBNUJaUkZKc2d0cmpW
        dTF1NVlnenlIZHAxMkdnOHVoQXlGMG5HK1FzCkxZU205Z0ViazlSUTNQZ3g3Snhu
        dGxnWXE4dCsyWmFhSFlFdWo5ZDQ3YmsKLS0tIERQbVlKYTAzd3ltZmRiZ2VsMThE
        WFZsZXl2YTJ1RWxZc09IQkZmTmNZZ1EKSPgln9CsEsIUHKZpF7zkWcVUi/QcM8k7
        duNq9FsnjuV4FLLx2ynCWA6NUQk1alcp+HLhyka31OUcvaZSeGOFDA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:35Z"
  mac: ENC[AES256_GCM,data:Bed5KJGwiPHV1s8YINpE+7RFHzMC+kG0bSpBn+nqMccTU+PFyyrbzEyzDEBBszm6I94oDBJito6mQl+I4CepnvraNehtuBZtzVXzptyvP6faXMlS8BsxsuWki28FplrbmnHEHFOEZEDUUoPpzMP+Cu4ZnNbXVDf7OfcLnssuJ64=,iv:sEWndal7v2UK5Y++JWgdstF95kRngrF1qBd0tZewmDg=,tag:mnFtgbOXFfEvsanGpghonA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
