apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:Tku8Ddn/m32Znic+A+0YsDyi+Mj5Yfx18wkvOc0LlyA0RM7n7JCHLV54uA4uaRvFLoZ30E/miZzW4MGiARvy9zb2OC6ySSzQzJ7/4pCAYcZdyP9IEa08UqOfqEKlk47b3epqrjRXww5SLQWKDc3wLI8DtCsmjI8S4FcQdZ2d5qJz5N0ZedbNrq6DmroUwvBgEs7HFGj11xNDVNVWIMJef+X4HA4JQ5PJ3PIBaJ4eUQU/6Lsl,iv:df7YSAwkUjuzvx7tHnrCAy+KlGHg0tZJwMXNMN7QAuw=,tag:cOSi901IaOR0ykF22oxGAQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQy9FTjVwMnNiaWhpVnVm
        ZTUrakY1b1ZualJXSlMzM3NoY3NyZG9iM0FFCjEwNmlIQkJiQzNybnZaMTJwL2Ju
        dDVvUTdOQ0x0dW10Z1dsTjNyU0I4S0EKLS0tIDVrQ0UyQmRDRENKNEc5dzdyYUNB
        aTNTYkYwWnZPWU1vVlpkRkRIclY5L0kK7On2mAB/Xvbn2TQCaZPpBMlfPsLljlHl
        GSYIY3Tf7JfIcpJLdltk4Ba8td2jnKdRR1raIuUPYtcs0Re5Qfqfdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:35Z"
  mac: ENC[AES256_GCM,data:btlfrk6YYqhl4Bu2YkoZvttMYwVSCpJb3t8srW+goS3RYHmd8Bb6CjgUKSu2vSBm1oOA44m03JaOM+xDYb6e0ktk6pwkt3eCE3VZetUdN63YCWeW01i5yzqCTroCvDgJ8Q3vLep0xN7mXGsJVFhKFUSdqQc9KrbjZR/aTlyr3BM=,iv:YpiHEjfQny8G030ohzRQoERZWJDfQDptQ7LsjCff7QA=,tag:WTMxGc1gkJKB2xsOJYQrbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
