apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:o8dsxyLRejMaqXKLTsM5TO6XtbrRKWQrpC49piIDZaTC2scs/VLc+tM/Ifz0ff3WfBkuP9oO654jfAa9OH5VbDM4hMMYfK/WVFTGfEFPD+r0qSRYOvuTBmDbpv/CTwJ6E0YMPWwwY51a3w3inLql3REhr4lCXBAOOIRDEqLOWRYM6WmpNnwgB/LF/XT++iH4byImA4cNQKl6+n9+aKMw9siONoJXXLNrYRESOxmkq98ri+HY,iv:xVBfF1AxBmVcGdrNzVHa3TbPQ+Gwu5ZR/ZxMMTSDDus=,tag:O/CrJQLCa9LyW6DHBaytrg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOGNNaFRWYzFFeEhQOCsv
        ZDE2dGwzWS81VWQ5WUZMSThsK0g5TXY4MHh3CldiSHNGKzRkZGhMcGZoSzJPMTBI
        aHNrSSt1SlZHSUtuVU9rUjc1U0NFbk0KLS0tICt2MW5nSG9JYkc3NlU1NWtvUlE1
        dVY5MFpiQnNnWEZFWEt6aTNDSjAxK1kKvX7bw63Zimn1avogW7tBhKKUQwRr5yCy
        kWjjfDBBiOyaFidT80dWRxiI3zwGylA/vDMC+USJwE5KNlWWMetzLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:NWAdXaSWrVCP7Z8iMwbMPDaokV/YjQ5eR9Sb4ITQZQuwos/XxBvp/vxao8yYtSl1ht+VnlhGTvjGTuzQ6MZnbWnSNWil+uz06ZJCHFIAEuWgVoZLq/q8rLviU9Xh4JQx45f3sXSwe/3iZHoD7Qug/pgShyjX+06roN/E2mSZjtw=,iv:r+W4XrbtRqg48ZhKR0XOcibCJ2Nkr06Nd1lsb7gWwCU=,tag:FiU4No+Ec0KRb6TFs7Ad6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
