apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:5pqwsCLzQqhatPffTWNIJUjbABQlvnoCmlSyb/mvwJ8ioJaxVPTEBjCEWMSRmIk71eH26bF9DTQLFQ34sxGbt2q7ivPATE5lFHme2tEn5o3ipA4dbiBtamDWpHQScJB9+1/8VW+WjpNzNa/QGgA4ll0PfJqUDIP1ffXF31kGdsD+O4TXw1aFp+k5T0F2EE9OQvomrQn8KKyk3TI4/Opoh//4SQ+z0rz90tQC01UvX30jox68,iv:mC8Gddk2acR/ClwMoNKivBxYKeonX0+EtXTHwJrel1Y=,tag:x/lxm2c18T5ZUn0X7eCyMQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTUlNvNzZDUzRERU0rRm94
        alVLZ2VCbm1rY3I4NkYzWkFWWk5SbVNsV1ZBClNldWxERDBibVJnTUNnTXI3emFj
        d2VxclM0UitXUUZ6dmRXM1ozc2RmcmsKLS0tIGUzdmJ3b3hzSmc3UmZpSHlzMU5w
        SXhmczUraUNDQUd4WmozNnN6a01obFkKwEywqvx+82KypxxMNk86FwK8XrP2cwXv
        83KSUs8UwcOLTn1yOc2WnxbU489LnE5CJLRoGXE6gEST6U69ERRvIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:03:55Z"
  mac: ENC[AES256_GCM,data:+ariWw3ptafjPR7uIEeCO1R4bZcfZAHzlw+lFFOOvWzIlwn4MAP2bIz7Wik8WJvF5f8BdsvIU5BPbi0l81eEqsLTQOQWWo+uXM0rP0WRkfyMeviwD4iSVfI5FecAokhrIX3ebrthHfsVTZlYUC0zZ8oJzZlZCnUsnIb7g+LKS/A=,iv:TdICUthME6daiYVj1VWu9XXBVCHZqWAYvXHQbMAQfAQ=,tag:43L+uewCIbux65jYKcuFuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
