apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:8Z0VqXCgfXLfpgKLfnximofT1o70RM3fGtz9ugb7uYUVD6SnrLCdz5RmA+zL5wLdOt16kpomRanEZHpMqOu7QyYxVW+ZTj19+ZWqDgdifXtsRNuBHoNvZdJOiIaAyt26uYTMzUTV+TM7MqNqtm+eg8UoBa+blx256CcB9UG3hXriyfs23unuhmz5pcZOf8ZaGnmDiyOJevdhdgvGGA+UpIoHo35+FWl4Tn8q+/EvsErwQcyY,iv:lK52TJQUtUZdpk6A656jmJuH7riK1I9AobbsHr4DL38=,tag:Vz8GL7wFlScKvjh5FwTpFA==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbk9zVG11Vnh4a1hndDBW
        elQ3SXdQc0VOU3djUW5OcFhtL3BWdldkYUFVCnFOendsZ1NSQ1M2RlAxeGljYnVF
        OWNIVGE5OEpyZWFhMjY4Q3dUQm1oU3cKLS0tICtJbURXdE94SkE3NCtvenRBQjh3
        SU1BWWdZditnc2RQQ2kwTUp0RnZuMVEKxVRarKQeJYf7FxQA3CNa6U0yaO6oZ8AA
        ok0Ib+tgLkrwzWo1U2TfvfQR/eCcWi5hky0ojcY5e+6MZYPUuHJo0g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:WRpNs7VY4tdryEmANbtfU6zwqRBaLBR+Usm0e5iUbKKd+LNOHuD9gp2H0TVlp4Z2sPb7SLK0iEtupGYOEEZJcpD35uWV2n2PlqwAj+hSN+0RWm6NVqml0hBezgZA2OlZ/cnuIV+EyLQTyUpcrHQl6UM7myBJrFiTBmDfhq+z4wY=,iv:GSahxsR8J93zD44y89Dg/nAmqOk6brTSTSLwZpSYNSc=,tag:Jn3Fb7z+jQk9YY6LlDGY0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
