apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:TUfxdqiaYCki9GytuD06aAQZT63IEWMWbLxwtyRJSSTFzuPOA7BjlckAV5FEvhwh5s0keYPeYdA/1k3aaWVashtMl1qV5lS6Ucm4xddFbefTdcIwra0+AqfgFT1uhfFe7mpxyZucohfZOXvYQshXBOYETL0zfrrQw7qKgtxcjIgj87z9uWPA5fMq8c8MUSyjyxJQ3LQRPewMuh8dw21LE0gNfMDW2O1EalBxzL6863UxfBCF,iv:Vv50pikku6vxg01CCfHa6HqwipRJgvMczWBzNjl9yS8=,tag:BbcYL2OpjXlH8QuW97MgAQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUEVwc1BUWTVZVlAxQXkr
        USsxeXA5bjIzK0NUMXU3ellzODBVTDg2T0UwCnA2b0NZanNnbXIzeHc1SnlxTHV6
        L1puTGwzODExNS9KamgzKzAyaXRWYW8KLS0tIFFqRXBFdVJNSDNkeTU0Zmk5NTVE
        UnhIaXlSZHgyeDYzNGFYMnhpczRQclEK/FKsbaN/prj5H2pWWwQwJnqOAdjt/F52
        annhqIM24UsvnJ1aDZLoVdxKFMAJDjf/EOxxIeZzF0hIzC4jBdeVRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:dd4E+CzekBNVG+huW4LjdPgVlW+lBTdnnSODeaz+3sI2tok/gtzuPZCE7e9dP+Pv3UMduxq8G1jeyvTOphLQKCi/NdZWowDPEX3AIH6jqHqaemnos83H6DLHsFY2AqBtu5yuorA0s5UjLPyRwi7zSNSwtYPPYZzqTIccNOpW09U=,iv:gSAZglucYwiEfUoAuESC17m68EuzxwwsTLAsyR6Rilk=,tag:64TaLEN8YKhVSgw9801qgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
