fullnameOverride: k8s-gateway
domain: k8s.krapulax.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 10.0.40.153
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIMldZamtCdXZEK3FBckd0
        bUM0dlk3UURIOWRtK0E5Y1lBbm56eVprajFzCndjc2tVVzVnQnIwMHM0a2NjaWhI
        U3RWWEhEZ0NrM3ZFN0lVdUxzVkFwWlUKLS0tIFFTM1NuVFRXVGtRZ3BzOXJDZ3Fx
        SXZuYlFSajZ4bW50TXNEL0tkNlZ0OXcK1Dina+nYVH00ZF7erQX+mIv8YNxrDjgp
        c36rZplnmKnAdEoQZYz1j9WApx+7oGBGRGqJwh37fyjSIFBhncZ12Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:PcFzEjIFtzJZ3Kh5EuuiOd0yw0CMKmBp2G6HnhbE5cN2Hse0L6IvagSiKY3ew2wpR0vQ6tDYXLykXJqDOycOHsEQ2PDPI6ufitOlGtNEVId3UbnuHJOr+RzHy7GRtNdLgviHF5w8hDeq2lUPbIwBENYECVrNWTHskri/6ZsC4Vc=,iv:E5Vv2vEyjukqZjVWvsWjefFziVansNzOauGui12PaNI=,tag:NqaO5ymNVKkz2B+f2KKRFg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
