fullnameOverride: k8s-gateway
domain: k8s.krapulax.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 10.0.40.153
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRFhtZDdpUXFQQWNpQWJj
        b09IVE9acXUrVXJuaGlLdzU0YlhWRnYrNlJZClNYM091eGx0N1haZmUwV0hBNjRq
        Ri91RCsxZ2o4djZJVTBBZDZaR3ZQamsKLS0tIFlhc2RRWUZHWkpZaUdDZDNMWkN5
        SHkrMU1NMGlDc0FEZDQrdXNoU2lDcTgK0tdBnRJt8xsv06QHPT7dREHyLcZCIZ5m
        YTPWBZTnnvi507XfEY8EuyzYWly1hjUbofBpWwgXxntJWbkKCtnbIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:7AspwaW79o4GCFyWhbMqGR8Y/Q5R41jsM3933OI4G6aSDX08WiNk9fNYkDVpIcJCGrHzcVPezR8VQ7VHqNE1N2ycrkADmDt43fcNoojHaU8VcaQLnpxfSBuEb5dTKU+dupwvvESUAv2+l+Owv0PSM8y2XaKfXMpGBxqsMaBF5Wk=,iv:SBfaxKeE3NxTlhnhwCoD9Ae7njZpLYzrjjgNPSa3Bpo=,tag:/lbMVLlcYkNfBk4zyAffIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
