fullnameOverride: k8s-gateway
domain: k8s.krapulax.dev
ttl: 1
service:
  type: LoadBalancer
  port: 53
  annotations:
    io.cilium/lb-ipam-ips: 10.0.40.153
  externalTrafficPolicy: Cluster
watchedResources:
  - HTTPRoute
  - Service
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZS1ZONHJlU294T1kvbDlY
        QXNsbExOMEhRUVBRNXRTc2RRNWVZWVlROEdRCmJiRitqa0pVYy9tV1V2dXh1TG9G
        RmpKNG5WZlNnaFhpNWJCQ2g0UHhKUFEKLS0tIFF6cGxQWDRlU2hPdGl5eGRYajRw
        WEhxeDVJK1I2TXB6Z1k3bUtEeFBnU2cKm6i2CfWE024oUgbH01vljhXk5oQ5TCnA
        sfxJvBKMhTl4nXGbtNWaclKfXhzYr4CCSuuvf1z5DaoYFkyCqt1JZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T16:28:02Z"
  mac: ENC[AES256_GCM,data:pid9sJeq5oMUXpyY0v9MXt5S1HqhGDm6TXiINdW6A/JWR4HWlRlxVAurUS6pPXYoBcoan7IPRlUxy53olQC0e/wLziY1Dq81sce+JTi2HMSL4bVa3LlXs3QvzxAG7vuxWS+79XbFyMpPglBK0y4JlIox4v3wv2eM9AtZTwD236w=,iv:r6LislSZz1pzqoZ12/918ShPyRQLw4Pt3JqvhU2IbBs=,tag:Jtn78gIq9auC02Jq+EilhA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
