apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:PNIQ/0y0oYd/pGP+VEtir0r/0D6RM+jeKTv34Yjbe8qbwUT8Jvd+Sw==,iv:reHpWxKLPeFfzQtNrL9qHbgBEGdbDJlexYx0/ruJeqQ=,tag:2Q4FCh36YPIMVkrHhTYprQ==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4V0Fvb21xcmdUMkQ2Z0Fl
        aTZpckRyRGkvczFibitvYzZhcHk4eVlmcDN3CkZSTkZzUFN2ZlVsZkZqdTdLRVNa
        ZytKczBvRDRnVEtqRnpCUDNUSUpWSEEKLS0tIG4wZStmRkRVUHFMOU1NZXBZOXc3
        QU45RFFEaXNYdndublRlcDRNVEJ2aGMKoXhqUgAu+BEa+lPk/Sg3P5tHa0vjW5ou
        1s1LzVoAoIHNyGscBIUM20E1CU/1aQ8lRZa+og/xvDNQb3R8jOAp7g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:03:55Z"
  mac: ENC[AES256_GCM,data:6XFgQHo+/s5Gdb6k3pWZZn6mcFqekXZCwr5pGv7k+IxIQYrGWweNWsf3KaW23YwFjf0U0KaSz6k8HCeTKznnFCrX7fIukVTNxbEBs5DxoVrIeaTI+G8K26LIEfTooYNS2swuEWXamSt8qlAZqHN5izZAS255YQmn67+NaO1NCZw=,iv:7+wew0QppDwFuNVtihyTeNHemI+mtpcQ/D5TeZtKtJ0=,tag:Ki7QgsaK6h/G9faV4ImluA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
