apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:9EJm/QacnpQF2I0O0+WWU8Hu6wSWVOBVm606aEUm8LcDSqWn2hKHGA==,iv:iD9k+3OOYmRpFHYqR0NgDwNiTTr0Nvytn5mKeDNVrbs=,tag:m/GNFqPEzfIbYhm3EtIg6g==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSTzdKRnN1VkovS2VFZDlk
        N0ZPRkVzdXRYOC9nMm1nOTltSjhjV1lHRVZNClZlczRBdkhueVlCRjJrakZLbHgz
        MG9GdldHV2ZiTFJ0SnZ4UmIzcWdCdmMKLS0tIFJUN3lLU1BzY3J1R2d0M2ZJZVZK
        eDE0U1lOMS9NTjErSmE2NFpJdzh1YTgKXZzC0E9g3StKkwuh7MZh+SnyXvqa2Kf/
        fLWgyUt8lYIaScPio/8XsxXVa8X+1P5K0zgR9c9+BoMDKmh8PSohJQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:34:35Z"
  mac: ENC[AES256_GCM,data:VKqzOqJ+VCGFMIkoLyrndz2wNXzSk/uPLajmov2HZ6g1d6joz0mS/Ri7SoPl2bKnwfg2Sf/Yo75fhGjVhHtLLL8K/DMbY3QC/cKQqnGgxAXSuTq9vv1jkMfVQg14clcQpA3CAetgSShvMcC9/YJfonmjyF6aOvzcYMNSfgtpIKc=,iv:kzTG5CHmoYohqlZFxFUK94Jrmeucnppsv7bDWjiDcrI=,tag:i6+EVQLzITGLVwDWNQ/aAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
