apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:GDP6U7Uk9enXapHpeFnVSlMa01son3lea5Si+Sh47vmMbFO+JNPZqQ==,iv:E4azpS5xkG0NfLBVXR30OeRcO9akE+kyps0lrO+P/8Y=,tag:IeR6gJbhiAIByxT+gPAHuw==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0VFV2ckxMSDh5SUdUQ3Rr
        MnBhMi9hZlhZcVh3bGoyMmdTWlRMaXhrVVNJClg1Q0t0ZWduSDZZL2sxNVoyOG9L
        aStma2RVb21KK1N6ZGhydGtLV3VxOUUKLS0tIEpyR0IwdmRIK3h0ZDJxeGxaREI3
        dHhBYmd1dnBuVDlVTGRtR3pjcVVUMHcKWb/QmOGY7t+qwxPuDzr701KimMPRApIl
        Hx80djoKpPXyvFCGl4UOZFaNBGsmvl3cwCZ6LsXtR0fszGl/bDJw/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T17:27:02Z"
  mac: ENC[AES256_GCM,data:9AkF6IxPYNyczRxYkEGrVLC1sFZE0i57MG38z7Qx35iXe3YjDO/B0K2IqjdA32LHFRfUmsLfsUCQWlU0H3dLHQ2ulaIRaIUvFME4dl7F74ldroJOs5Rl1YtP0YySqdaAasc7/ziBr1WsNoj0tQiW5ZG3m0YF0jSWrLUvFx9b7sI=,iv:OaFdkFitzo1nxXxsxg1t5BOpD5LGEoqcib70gQszLIk=,tag:rnM1NcMdwi9wby1dzfBPcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
