apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:rUXGzsCbBdoz/vLf9JMWyqLwupswC2+s+9rWaz5B6lTREXVJ6wP+wA==,iv:y4w9D6eB4nJNcmrCFlaDTfxzPBEOTwOJWFC5SQbfejc=,tag:p1YswKvDjex9BVnlRvGkRg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwUGVGMmVndzVrbi80QW5z
        WGFtbzR1QmF2MG1OWWw2NFRLUG5hNGlOYnpzCkhVT3BxUm9RWmZvZXlqOVNRTE5h
        akF5TnJZVDdvTytab2JHSnJlVDdIU2cKLS0tIFRYQ0phdVRzUHdpNEZHMFFBOGFo
        RTRkdUtOdVZCd1dWNWJTaG9GN2pNQ28KbhQzUINe/8n9koiRwj2aeo5M/8T0yCLz
        U1Reh7WDNDsaR51DJBz49rVUIGUVNKRqxRm6XvDw9JWhl3Rl3suZ+A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T15:44:12Z"
  mac: ENC[AES256_GCM,data:/DgW8bPhLs3dL5s3NEb2tT/TpupW5RyrGRP14z8BKDp2HaJlfBfBPuhBqWgL6t7dz410gv+TveyhhRSHMFgOdKooLM7HvJpuxxSxOEOWskiLNZ+nhHS7C2Bt9nfQ2pXQq0MpsRFah2c753mq9G3kRiqRFZEB/4uC+61C8m3ylpg=,iv:HWy/zO2tgYR046urccI6FBG0ih2K68fq95ATXRXhIsw=,tag:VhoCMsGXTeVfF3jWo3IjhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
